CodedEvents/CodedEvents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from backend.swagger_schema import SwaggerSchemaView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
import backend.pages as pages

schema_view = get_schema_view(
   openapi.Info(
      title="KitKat API",
      default_version='v1',
      description="Event Ticketing API endpoint",
      contact=openapi.Contact(email="contact@coded.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # Authentication
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    #API
    # url(r'', include('backend.urls')),
    re_path(r'^api/v1/', include('backend.urls')),
    url(r'^swagger/$', SwaggerSchemaView.as_view()),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    #Pageviews
    path('backend/', pages.index, name='index'),
    path('backend/admin/events', pages.AdminEventList, name='admin_event_list'),
    path('backend/admin/events/new', pages.AdminEventAdd, name='admin_event_add'),
    path('backend/admin/orders', pages.AdminOrdersList, name='admin_event_orders'),
    path('backend/events/view/<int:id>', pages.EventView, name='event_view'),      
    path('backend/cart', pages.CartView, name='cart_view'),
]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

CodedEvents/backend/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter

#Register routes
router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'roles', RolesViewSet)
router.register(r'ticket', TicketViewSet)
router.register(r'event', EventViewSet)
router.register(r'booking', BookingViewSet)
router.register(r'address', AddressViewSet)
router.register(r'category', CategoryViewSet)

urlpatterns = [
    url(r'', include(router.urls)),
    path('oauth/', include('backend.oauth')),
]

CodedEvents/backend/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from .managers import CustomUserManager
from django.utils import timezone

# TODO: Add more commenting/explanation
# TODO: Create tests for these models, perhaps using django-faker
# TODO: Explain attributes i.e. on_delete
class Role(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=100)


# This extend the default User model provided by Django, this allows you to store
# non-auth related information about a user.
class Profile(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    roles = models.ManyToManyField(Role)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Address(models.Model):
    street = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=100, null=True)
    province = models.CharField(max_length=30, null=True)
    code = models.CharField(max_length=30, null=True)

    class Meta:
        verbose_name_plural = 'Addresses'


class Category(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'


class Event(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=100)
    organizers = models.ManyToManyField(Profile)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    tickets_available = models.IntegerField(default = None)
    check_ins = models.IntegerField(default = None)
    start_time = models.DateTimeField(default  = None, blank = False, null = False)
    end_time = models.DateTimeField(default = None, blank = False, null = False)
    registration_opens = models.DateTimeField(default = None)
    categories = models.ManyToManyField(Category)


class Ticket(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    quantity = models.IntegerField(default = None, blank=False, null=False)
    ticket_desc = models.CharField(max_length=30)
    price = models.FloatField(default = None, blank=False, null=False)
    status = models.CharField(max_length=30)
    shut_off_time = models.DateTimeField(default = None, blank = False, null = False)


class Booking(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    total_paid = models.FloatField(default = None, blank=False, null=False)
    transaction_id = models.CharField(default = None, max_length=30)

class BookingInstance(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    quantity = models.IntegerField(default = None, blank=False, null=False)
    created_at = models.DateTimeField(default  = None, blank = False, null = False)
    updated_at = models.DateTimeField(default = None, blank = False, null = False)

class Cart(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default  = None, blank = False, null = False)
    updated_at = models.DateTimeField(default = None, blank = False, null = False)

    def total(self):
        user_cart = Cart.objects.prefetch_related('cartinstance_set').get(id=self.id)
        user_total = 0

        for key, item in enumerate(user_cart.cartinstance_set.all()):
            user_total += item.total()

        return user_total

class CartInstance(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    quantity = models.IntegerField(default = None, blank=False, null=False)
    created_at = models.DateTimeField(default  = None, blank = False, null = False)
    updated_at = models.DateTimeField(default = None, blank = False, null = False)

    def total(self):
        return self.quantity * self.ticket.price

CodedEvents/backend/forms.py
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from backend.models import *
from django.forms.models import fields_for_model,model_to_dict
from django import forms
from django.forms import formset_factory, BaseFormSet
from django.shortcuts import get_object_or_404

class EventBaseForm(forms.ModelForm):
    name = forms.CharField(max_length=30, required=False)
    desc = forms.CharField(max_length=100, required=False)
    tickets_available = forms.IntegerField(required=False)
    organizers = forms.ModelMultipleChoiceField(queryset=Profile.objects.all(), required=False)

    class Meta:
        model = Event
        fields = ('name', 'desc', 'tickets_available', 'organizers')

class EditEventForm(EventBaseForm):
    ticket_desc = forms.CharField(max_length=30, required=False)
    quantity = forms.IntegerField(required=False)
    price = forms.FloatField(required=False)
    status = forms.CharField(max_length=30, required=False)
    shut_off_time = forms.DateTimeField(required=False)

    class Meta(EventBaseForm.Meta):
        fields = EventBaseForm.Meta.fields + ('ticket_desc', 'price','quantity', 'status', 'shut_off_time')
    
    def save(self, commit=True, ticket=None):
        instance = super(EditEventForm, self).save(commit=False)

        # Check if ticket instance was passed in arguments
        if ticket == None:
            ticket = Ticket()

        # Check if all values filled and save to ticket instance
        setattr(ticket, 'ticket_desc', self.cleaned_data['ticket_desc'])
        setattr(ticket, 'quantity', self.cleaned_data['quantity'])
        setattr(ticket, 'price', self.cleaned_data['price'])
        setattr(ticket, 'status', self.cleaned_data['status'])
        setattr(ticket, 'shut_off_time', self.cleaned_data['shut_off_time'])
        setattr(ticket, 'event_id', instance.id)

        ticket.save()
        # if commit:
        #     instance.save()
        return instance

class AddEventForm(forms.ModelForm):
    name = forms.CharField(max_length=30)
    desc = forms.CharField(max_length=100)
    tickets_available = forms.IntegerField()
    organizers = forms.ModelMultipleChoiceField(queryset=Profile.objects.all())
    address = forms.ModelMultipleChoiceField(queryset=Address.objects.all())
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all())
    check_ins = models.IntegerField(default = None)
    start_time = models.DateTimeField(default  = None, blank = False, null = False)
    end_time = models.DateTimeField(default = None, blank = False, null = False)
    registration_opens = models.DateTimeField(default = None)

    class Meta:
        model = Event
        fields = ['name', 'desc', 'tickets_available', 'organizers', 'end_time', 'start_time', 'check_ins', 'registration_opens', 'categories', 'address']
        exclude = ['address', 'categories', 'organizers']

    def clean_address(self):
        address_id = self.cleaned_data.get('address')

        try:
            self.address = Address.objects.get(pk=self.data['address'])
        except Address.DoesNotExist:
            raise forms.ValidationError('Sorry, that address id is not valid.')

        return address_id
    
    def clean_categories(self):
        categories_id = self.cleaned_data.get('categories')
        try:
            self.categories = Category.objects.get(pk=self.data['categories'])
        except Category.DoesNotExist:
            raise forms.ValidationError('Sorry, that category id is not valid.')

        return categories_id

    def clean_organizers(self):
        organizers_id = self.cleaned_data.get('organizers')
        try:
            self.organizers = Profile.objects.get(pk=self.data['organizers'])
        except Profile.DoesNotExist:
            raise forms.ValidationError('Sorry, that profile id is not valid.')

        return organizers_id

    def save(self, commit=True):
        instance = super(AddEventForm, self).save(commit=False)

        instance.address = self.address
        instance.save()
        instance.categories.add(self.categories)
        instance.organizers.add(self.organizers)
        if commit:
            instance.save()
        return instance

class BuyTicketForm(forms.ModelForm):

    class Meta:
        model = CartInstance
        fields = ['ticket', 'quantity', 'created_at', 'updated_at']
        exclude = ['cart']

    def __init__(self, *args, **kwargs):
        super(BuyTicketForm, self).__init__(*args, **kwargs)

        for i in list(self.fields.keys()):
            v = self.fields[i]
            self.fields["{}_{}".format(v, i)] = forms.CharField()

class BaseTicketFormSet(BaseFormSet):
    def clean(self):
        """Checks that no two articles have the same title."""
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        titles = []
        for form in self.forms:
            if self.can_delete and self._should_delete_form(form):
                continue
            title = form.cleaned_data.get('ticket')
            if title in titles:
                raise forms.ValidationError("Articles in a set must have distinct titles.")
            titles.append(title)

CodedEvents/backend/views/address.py
from backend.models import Address
from backend.serializers import AddressSerializer
from rest_framework import viewsets


class AddressViewSet(viewsets.ModelViewSet):
    """
    retrieve:
        Return a address instance.

    list:
        Return all address, ordered by most recently joined.

    create:
        Create a new address.

    delete:
        Remove an existing address.

    partial_update:
        Update one or more fields on an existing address.

    update:
        Update a address.
    """
    queryset = Address.objects.all()
    serializer_class = AddressSerializer

CodedEvents/backend/views/booking.py
from backend.models import Booking
from backend.serializers import BookingSerializer
from rest_framework import viewsets


class BookingViewSet(viewsets.ModelViewSet):
    """
    retrieve:
        Return a booking instance.

    list:
        Return all booking, ordered by most recently joined.

    create:
        Create a new booking.

    delete:
        Remove an existing booking.

    partial_update:
        Update one or more fields on an existing booking.

    update:
        Update a booking.
    """
    queryset = Booking.objects.all()
    serializer_class = BookingSerializer

CodedEvents/backend/views/category.py
from backend.models import Category
from backend.serializers import CategorySerializer
from rest_framework import viewsets


class CategoryViewSet(viewsets.ModelViewSet):
    """
    retrieve:
        Return a category instance.

    list:
        Return all category, ordered by most recently joined.

    create:
        Create a new category.

    delete:
        Remove an existing category.

    partial_update:
        Update one or more fields on an existing category.

    update:
        Update a category.
    """
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

CodedEvents/backend/views/event.py
from backend.models import Event
from backend.serializers import EventSerializer
from rest_framework import viewsets


class EventViewSet(viewsets.ModelViewSet):
    """
    retrieve:
        Return a event instance.

    list:
        Return all event, ordered by most recently joined.

    create:
        Create a new event.

    delete:
        Remove an existing event.

    partial_update:
        Update one or more fields on an existing event.

    update:
        Update a event.
    """
    queryset = Event.objects.all()
    serializer_class = EventSerializer

CodedEvents/backend/views/roles.py
from backend.models import Role
from backend.serializers import RoleSerializer
from rest_framework import viewsets


class RolesViewSet(viewsets.ModelViewSet):
    """
    retrieve:
        Return a role instance.

    list:
        Return all role, ordered by most recently joined.

    create:
        Create a new role.

    delete:
        Remove an existing role.

    partial_update:
        Update one or more fields on an existing role.

    update:
        Update a role.
    """
    queryset = Role.objects.all()
    serializer_class = RoleSerializer

CodedEvents/backend/views/ticket.py
from backend.models import Ticket
from backend.serializers import TicketSerializer
from rest_framework import viewsets

class TicketViewSet(viewsets.ModelViewSet):
    """
    retrieve:
        Return a ticket instance.

    list:
        Return all ticket, ordered by most recently joined.

    create:
        Create a new ticket.

    delete:
        Remove an existing ticket.

    partial_update:
        Update one or more fields on an existing ticket.

    update:
        Update a ticket.
    """
    queryset = Ticket.objects.all()
    serializer_class = TicketSerializer

CodedEvents/backend/views/user.py
from django.contrib.auth.models import User
from backend.models import Profile
from backend.serializers import ProfileCreateSerializer, ProfileSerializer
from rest_framework import viewsets

# TODO: Override perform_create to use customUserManager. 
class UserViewSet(viewsets.ModelViewSet):
    """
    retrieve:
        Return a user instance.

    list:
        Return all users, ordered by most recently joined.

    create:
        Create a new user.

    delete:
        Remove an existing user.

    partial_update:
        Update one or more fields on an existing user.

    update:
        Update a user.
    """
    queryset = Profile.objects.all()
    method_serializer_classes = {
        ('GET', ): ProfileSerializer,
        ('POST', 'PUT', 'PATCH'): ProfileCreateSerializer
    }
    
    '''
    Utility class for get different serializer class by method.
    For example:
    method_serializer_classes = {
        ('GET', ): MyModelListViewSerializer,
        ('PUT', 'PATCH'): MyModelCreateUpdateSerializer
    }
    '''
    def get_serializer_class(self):
        assert self.method_serializer_classes is not None, (
            'Expected view %s should contain method_serializer_classes '
            'to get right serializer class.' %
            (self.__class__.__name__, )
        )
        for methods, serializer_cls in self.method_serializer_classes.items():
            if self.request.method in methods:
                return serializer_cls

        raise exceptions.MethodNotAllowed(self.request.method)

CodedEvents/backend/templates/index.html
{% extends "master_layout.html" %}

{% block content %}
<div id="slider" class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#slider-carousel" data-slide-to="1"></li>
                    <li data-target="#slider-carousel" data-slide-to="2"></li>
                </ol>

                <div class="carousel-inner">
                    <div class="item active">
                        <div class="col-sm-6">
                            <h1><span></span></h1>
                            <h2>Great Events! Great Ticket Prices!</h2>
                            <p>Prices are very affordable</p>
                            <button type="button" class="btn btn-default slider-purchase-btn accent-bg-0"><a class="accent-0" href="#">Buy Tickets Now</a></button>
                        </div>
                        <div class="col-sm-6">
                            <img src="https://d3clc8w717qc4g.cloudfront.net/assets/audioblocks/images/home/guitarist_hero.png" width="500px" height="500px" class="img-responsive" alt="" />
                        </div>
                    </div>
                    <div class="item">
                        <div class="col-sm-6">
                            <h1><span></span></h1>
                            <h2>Great Events! Great Ticket Prices!</h2>
                            <p>Prices are very affordable</p>
                            <button type="button" class="btn btn-default slider-purchase-btn accent-bg-0"><a class="accent-0" href="#">Buy Tickets Now</a></button>
                        </div>
                        <div class="col-sm-6">
                            <img src="https://d3clc8w717qc4g.cloudfront.net/assets/audioblocks/images/home/guitarist_hero.png" class="img-responsive" alt="" width="500px" height="500px"/>
                        </div>
                    </div>

                    <div class="item">
                        <div class="col-sm-6">
                            <h1><span></span></h1>
                            <h2>Great Events! Great Ticket Prices!</h2>
                            <p>Prices are very affordable</p>
                            <button type="button" class="btn btn-default slider-purchase-btn accent-bg-0"><a class="accent-0" href="#">Buy Tickets Now</a></button>
                        </div>
                        <div class="col-sm-6">
                            <img src="https://newvitruvian.com/images/adele-transparent-2.png" class="img-responsive" alt="" width="500px" height="500px"/>
                        </div>
                    </div>

                </div>

                <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                    <i class="fa fa-angle-left"></i>
                </a>
                <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                    <i class="fa fa-angle-right"></i>
                </a>
            </div>

        </div>
    </div>
</div>

    <div id="shopper" class="">
      <div class="row">
        <div class="col-sm-12 padding-right">
          <div class="features_items">
            <h2 class="title text-center"> Events List </h2>
          </div>
          {% if event_list %}
            {% for event in event_list %}
              <div class="col-sm-5 col-md-3">
                <div class="thumbnail product">
                  <img src="http://www.placehold.it/120x120" class="img-responsive">
                  <div class="caption" style="text-align:center;">
                    <p style="font-weight: 400; color: #131416; margin: 0 0 10px 0;">{{ event.name }}</p>
                    <p class="accent-2">{{ event.desc }}</p>
                    <p><a href="/backend/events/view/{{event.id}}" class="btn btn-product accent-bg-0 accent-0" role="button"><span class="fa fa-shopping-cart"></span> View</a> </p>
                  </div>
                </div>
              </div>
              {% endfor %}
              {% endif %} 
        </div>
      </div>
    </div>
    <script>
    /*price range*/
     $('#price-slider').slider();
    </script>
{% endblock %}